import {Component, ElementRef, OnDestroy, OnInit, ViewChild} from '@angular/core';
import Modeler from "bpmn-js/lib/Modeler";
import CustomRules from "./custom/custom-rules";
import {CustomRenderer} from "./custom/custom-renderer";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
  @ViewChild('bpmnModeler', {static: true}) bpmnModeler!: ElementRef<HTMLDivElement>;
  title = 'bpmn-angular';
  modeler!: any;
  canvas!: { zoom: (zoomValue?: number | string, mode?: string) => number; resized: () => void };
  xml = `<?xml version="1.0" encoding="UTF-8" standalone="no"?><bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:ipi="http://www.infor.com/ipi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="Definitions_1" name="Text issue" targetNamespace="http://bpmn.io/schema/bpmn"><bpmn:extensionElements><ipi:attribute name="new_cust2" value="true"/><ipi:attribute name="new_cust4" value="1"/><ipi:attribute name="aaaa" value="&quot;&quot;"/><ipi:attribute name="prs00003" value="&quot;&quot;"/><ipi:attribute name="prs00002" value="&quot;&quot;"/><ipi:attribute name="processownerv1" value="&quot;&quot;"/><ipi:attribute name="continent" value="&quot;&quot;"/><ipi:attribute name="model" value="&quot;&quot;"/><ipi:attribute name="new_cust" value="&quot;&quot;"/><ipi:attribute name="rt24v11jiraipit200custattr1" value="&quot;&quot;"/><ipi:attribute name="vittorioattribute" value="&quot;&quot;"/><ipi:attribute name="spacef" value="&quot;&quot;"/><ipi:attribute name="gru" value="&quot;&quot;"/><ipi:attribute name="sktest" value="&quot;&quot;"/><ipi:attribute name="name" value="{&quot;id&quot;:567009,&quot;uuid&quot;:&quot;0674096c-31bb-7d07-8c00-151c7432fd40&quot;,&quot;type&quot;:&quot;registry&quot;,&quot;name&quot;:&quot;Text issue_298cb2f2088141e4a467f162b1449b32&quot;,&quot;title&quot;:&quot;Text issue&quot;,&quot;autoGenerated&quot;:true,&quot;translationLanguage&quot;:&quot;en-US&quot;,&quot;inforStandard&quot;:false}"/></bpmn:extensionElements><bpmn:process id="Process_1" isExecutable="false"><bpmn:startEvent id="StartEvent_1"><bpmn:extensionElements><ipi:attribute name="new_cust4" value="1"/><ipi:attribute name="prs00003" value="&quot;&quot;"/><ipi:attribute name="prs00002" value="&quot;&quot;"/><ipi:attribute name="new_cust" value="&quot;&quot;"/><ipi:attribute name="rt24v11jiraipit200custattr1" value="&quot;&quot;"/><ipi:attribute name="vittorioattribute" value="&quot;&quot;"/><ipi:attribute name="spacef" value="&quot;&quot;"/><ipi:attribute name="gru" value="&quot;&quot;"/><ipi:attribute name="sktest" value="&quot;&quot;"/></bpmn:extensionElements></bpmn:startEvent><bpmn:group categoryValueRef="CategoryValue_161dsgn" id="Group_1ku6qli" name="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the "><bpmn:documentation/><bpmn:extensionElements><ipi:attribute name="new_cust4" value="1"/><ipi:attribute name="prs00003" value="&quot;&quot;"/><ipi:attribute name="prs00002" value="&quot;&quot;"/><ipi:attribute name="new_cust" value="&quot;&quot;"/><ipi:attribute name="rt24v11jiraipit200custattr1" value="&quot;&quot;"/><ipi:attribute name="vittorioattribute" value="&quot;&quot;"/><ipi:attribute name="spacef" value="&quot;&quot;"/><ipi:attribute name="gru" value="&quot;&quot;"/><ipi:attribute name="sktest" value="&quot;&quot;"/><ipi:attribute name="name" value="{&quot;id&quot;:567010,&quot;uuid&quot;:&quot;0674096c-31d0-73a5-9400-f6e3806b3a99&quot;,&quot;type&quot;:&quot;registry&quot;,&quot;name&quot;:&quot;Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the _46f8c66bda044635be3d9702b7dbe198&quot;,&quot;title&quot;:&quot;Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the &quot;,&quot;autoGenerated&quot;:true,&quot;translationLanguage&quot;:&quot;en-US&quot;,&quot;inforStandard&quot;:false}"/></bpmn:extensionElements></bpmn:group></bpmn:process><bpmn:category id="Category_19b4oqo"><bpmn:categoryValue id="CategoryValue_161dsgn" value="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the "/></bpmn:category><bpmndi:BPMNDiagram documentation="" id="BPMNDiagram_1"><bpmndi:BPMNPlane bpmnElement="Process_1" id="BPMNPlane_1"><bpmndi:BPMNShape bioc:fill="#25AF65" bioc:stroke="#000000" bpmnElement="StartEvent_1" id="_BPMNShape_StartEvent_2"><dc:Bounds height="36" width="36" x="173" y="102"/></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement="Group_1ku6qli" id="Group_1ku6qli_di"><dc:Bounds height="300" width="300" x="41" y="-220"/><bpmndi:BPMNLabel><dc:Bounds height="106" width="78" x="152" y="-213"/></bpmndi:BPMNLabel></bpmndi:BPMNShape></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></bpmn:definitions>`;

  async ngOnInit(): Promise<void> {
    this.modeler = new Modeler({
      keyboard: {bindTo: document},
      container: this.bpmnModeler.nativeElement,
      additionalModules: [
        {
          __init__: ['customRenderer','resizeTasks'],
          customRenderer: ['type', CustomRenderer],
          resizeTasks: ['type', CustomRules],
        },
      ],
    });
    this.canvas = this.modeler?.get('canvas');
    await this.renderDiagram(this.xml);
  }

  private async renderDiagram(xml: string) {
    try {
      await this.modeler.importXML(xml);
    } catch (error) {
      console.log(error)
    }
    this.centerModel();
  }

  private centerModel() {
    const zoomVal = this.canvas?.zoom('fit-viewport', 'auto');
    this.canvas?.zoom(zoomVal - 0.07, 'auto');
  }

  ngOnDestroy(): void {
    this.modeler?.clear();
  }

}
